### ISSUE TITLE
【教程】XiGua视频DRM手动解密

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/Blog#17]
---
>  仅技术讨论学习，请勿用于非法用途
---

以`https://www.ixigua.com/cinema/album/85dS526nogC/?logTag=epq5lhhbOxZskD-YlXjwY`为例：

## 获得KEY

过滤`play_licenses`，复制出对应的`KID`和`加密key`备用

![image](https://user-images.githubusercontent.com/20772925/75517967-e2544d00-5a3a-11ea-89b9-74b63b648cd2.png)

在`console`中执行脚本，来源[点我](https://s3.pstatp.com/toutiao/xigua_video_web_pc/static/js/vendors~xgplayer_encrypt.b05f677a.chunk.js)
```js
function str2hex (e) {
 if ("" === e)
        return "";
    for (var t = [], r = 0; r < e.length; r++)
        t.push(e.charCodeAt(r));
    return t
}

var tt1 = window.atob("m+ZPqQW2SvxrsnGpOucmxjjkGqsAt03+VOMZ/lLlGvJQ0EqoqA==");
var tt2 = str2hex(tt1);
var tt3 = window.Module._malloc(Number(tt2.length));
window.Module.HEAP8.set(tt2, tt3);
var p = window.Module._openBox(Number(tt3), tt2.length);
var f = window.Module.UTF8ToString(p);
console.log(f);
```

![image](https://user-images.githubusercontent.com/20772925/75518050-0ca60a80-5a3b-11ea-8e5c-ddf7a826079f.png)

## 下载分片
具体链接构造格式可以结合抓包和MPD文件观察

---
`mpd`文件中有详细的码率信息即分片信息：

![image](https://user-images.githubusercontent.com/20772925/73357575-98f7cd00-42d7-11ea-93e7-34faf9f0a4a3.png)

## 解密过程

前`1分钟`**没加密**，直接下载合并即可

`1分钟`之后的解密方式：

将`1_init`与后面所有分片**二进制合并**为`test.mp4`，用上面的`KID`和`解密好的KEY`开始进行解密

```
mp4decrypt.exe --key 5e306e5dc8d2ea26b24e3bfe0002043b:0ea5fa9d12ce49789f23ea24e5d3a0d8 test.mp4 2.mp4
```

最后合并即可：
```
ffmpeg -i concat:"1.mp4|2.mp4" -c copy "final.mp4"
```

![image](https://user-images.githubusercontent.com/20772925/73362098-2b509e80-42e1-11ea-9215-21d7fb794993.png)

音频同理

附：
http://zebulon.bok.net/Bento4/binaries/Bento4-SDK-1-5-1-629.x86-microsoft-win32-vs2010.zip

**Comment by nilaoda** [comment]
## 辅助脚本

本脚本将解析MPD文件并生成[N_m3u8DL-CLI](https://github.com/nilaoda/N_m3u8DL-CLI)可以直接下载的m3u8文件。本人py辣鸡，不喜勿喷。

## 演示
下面以[亮剑第一集](https://www.ixigua.com/cinema/album/7YT7Ldsw66r_7YTlG7Uh3AO/?logTag=ZNRa4BxDzH5K1hNLiAz_H)为例，演示脚本

首先过滤`mpd`得到链接：

![image](https://user-images.githubusercontent.com/20772925/75522435-f1d89380-5a44-11ea-9293-b8b8a00cbdce.png)

然后过滤`lic`得到加密密钥：

![image](https://user-images.githubusercontent.com/20772925/75522481-103e8f00-5a45-11ea-9e57-311f8ca04a3e.png)

之后按照楼上教程得到真正密钥：

![image](https://user-images.githubusercontent.com/20772925/75522513-20ef0500-5a45-11ea-81c3-67d3c37efd49.png)


执行脚本，输入所需内容：

![image](https://user-images.githubusercontent.com/20772925/75522638-6b708180-5a45-11ea-8b3f-967488e42c07.png)


脚本执行完毕后的文件夹内容：

![image](https://user-images.githubusercontent.com/20772925/75522687-86db8c80-5a45-11ea-92e1-f00d79c5da28.png)

![image](https://user-images.githubusercontent.com/20772925/75522703-8f33c780-5a45-11ea-8c81-efb672134709.png)

---

开始下载两个`master`列表：

![image](https://user-images.githubusercontent.com/20772925/75522763-b094b380-5a45-11ea-8861-502dcf42e67f.png)

![image](https://user-images.githubusercontent.com/20772925/75522810-c86c3780-5a45-11ea-9209-c330ff936897.png)


下载结束后，文件夹内容：

![image](https://user-images.githubusercontent.com/20772925/75522988-2567ed80-5a46-11ea-8660-3cb9a6bae1ba.png)


然后双击`解密合并脚本.bat`（**确保目录下存在`mp4decrypt.exe`**）：

![image](https://user-images.githubusercontent.com/20772925/75523130-6c55e300-5a46-11ea-8a41-8df9a1febd5d.png)

执行完毕后得到了`MUX.mp4`即为最终文件

![image](https://user-images.githubusercontent.com/20772925/75523197-8263a380-5a46-11ea-8007-3b5c872cead0.png)


![image](https://user-images.githubusercontent.com/20772925/75523276-ad4df780-5a46-11ea-93c8-7d7dd4078ce1.png)

---
附：

```py
import os
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning
import sys
from xml.dom.minidom import parse
import xml.dom.minidom
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
import urllib.parse
import isodate
from  duration import to_seconds
import math
import re

mpd_url = input("请输入MPD链接:\n")
output_dir = input("\n请输入输出文件夹目录(如 C:\\Users\\nilao\\Downloads):\n")
KEY = input("\n请输入KEY:\n")
if not os.path.exists(output_dir+"/M3U8"):
    os.makedirs(output_dir+"/M3U8")

def getUrl(url1, url2):
    return urllib.parse.urljoin(url1, url2)

AUDIO_TRACK_1 = ['0'] #不加密
AUDIO_TRACK_2 = ['0'] #加密
VIDEO_TRACK_1 = []
VIDEO_TRACK_2 = []
    
#下载mpd文件
print("\n开始下载MPD文件")
xml_content = requests.get(mpd_url, verify=False).content
#print(xml_content)

#开始解析
print("开始解析MPD文件")
DOMTree = xml.dom.minidom.parseString(xml_content)
rootNode = DOMTree.documentElement
#总时长
totalDur = to_seconds(isodate.parse_duration(rootNode.getAttribute("mediaPresentationDuration")))
Period = rootNode.getElementsByTagName("Period")[0]
AdaptationSet = Period.getElementsByTagName("AdaptationSet")
for adaptation in AdaptationSet:
    #视频
    if adaptation.getAttribute("mimeType") == "video/mp4":
        Representation = adaptation.getElementsByTagName("Representation")
        #各个清晰度
        for dfn in Representation:
            bandwidth = dfn.getAttribute("bandwidth")
            codecs = dfn.getAttribute("codecs")
            res = dfn.getAttribute("width")+"x"+dfn.getAttribute("height")
            base = dfn.getElementsByTagName("BaseURL")[0].childNodes[0].data
            SegmentTemplate = dfn.getElementsByTagName("SegmentTemplate")[0]
            global KID
            KID = dfn.getElementsByTagName("ContentProtection")[0].getAttribute("cenc:default_KID").replace("-", "")
            init = SegmentTemplate.getAttribute("initialization")
            startNumber = int(SegmentTemplate.getAttribute("startNumber"))
            mediaFormat = SegmentTemplate.getAttribute("media") #1_$Number%04d$
            m = re.findall(r"(\w+)\$Number%(.*?)d\$", mediaFormat, re.S)[0]
            #前缀
            prefix = m[0]
            #补零长度
            zeroLen = int(m[1])
            duration = int(SegmentTemplate.getAttribute("duration")) / 1000
            init_url = getUrl(mpd_url, base)+init
            #构造m3u8文件
            m3u8_1 = "#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-PLAYLIST-TYPE:VOD\n#EXT-X-MAP:URI=\""+init_url+"\""
            m3u8_2 = "#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-PLAYLIST-TYPE:VOD\n#EXT-X-MAP:URI=\""+init_url+"\"\n#EXT-X-KEY:METHOD=cenc,URI=\"None\""
            for i in range(startNumber, math.ceil(totalDur/duration)+1):
                seg = getUrl(mpd_url, base)+prefix+str(i).zfill(zeroLen)
                #一分钟以后
                if i>60/duration:
                    m3u8_2 += "\n#EXTINF:"+str(duration)+",\n" + seg
                else:
                    m3u8_1 += "\n#EXTINF:"+str(duration)+",\n" + seg
            m3u8_1+="\n#EXT-X-ENDLIST"
            m3u8_2+="\n#EXT-X-ENDLIST"
            with open(os.path.join(output_dir, f"M3U8/未加密_video_track_{res}_{bandwidth}.m3u8"), "w") as f1:
                f1.write(m3u8_1)
            with open(os.path.join(output_dir, f"M3U8/加密_video_track_{res}_{bandwidth}.m3u8"), "w") as f1:
                f1.write(m3u8_2)
            #加入VIDEO_TRACK
            VIDEO_TRACK_1.append(f'#EXT-X-STREAM-INF:BANDWIDTH={bandwidth},AVERAGE-BANDWIDTH={bandwidth},CODECS="{codecs}",RESOLUTION={res},AUDIO="default-audio-group"\nM3U8/未加密_video_track_{res}_{bandwidth}.m3u8')
            VIDEO_TRACK_2.append(f'#EXT-X-STREAM-INF:BANDWIDTH={bandwidth},AVERAGE-BANDWIDTH={bandwidth},CODECS="{codecs}",RESOLUTION={res},AUDIO="default-audio-group"\nM3U8/加密_video_track_{res}_{bandwidth}.m3u8')
    #音频
    elif adaptation.getAttribute("mimeType") == "audio/mp4":
        Representation = adaptation.getElementsByTagName("Representation")
        #各个清晰度
        for dfn in Representation:
            bandwidth = dfn.getAttribute("bandwidth")
            base = dfn.getElementsByTagName("BaseURL")[0].childNodes[0].data
            SegmentTemplate = dfn.getElementsByTagName("SegmentTemplate")[0]
            init = SegmentTemplate.getAttribute("initialization")
            startNumber = int(SegmentTemplate.getAttribute("startNumber"))
            mediaFormat = SegmentTemplate.getAttribute("media") #1_$Number%04d$
            m = re.findall(r"(\w+)\$Number%(.*?)d\$", mediaFormat, re.S)[0]
            #前缀
            prefix = m[0]
            #补零长度
            zeroLen = int(m[1])
            duration = int(SegmentTemplate.getAttribute("duration")) / 1000
            duration_count = 0
            init_url = getUrl(mpd_url, base)+init
            #构造m3u8文件
            m3u8_1 = "#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-PLAYLIST-TYPE:VOD\n#EXT-X-MAP:URI=\""+init_url+"\""
            m3u8_2 = "#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-PLAYLIST-TYPE:VOD\n#EXT-X-MAP:URI=\""+init_url+"\"\n#EXT-X-KEY:METHOD=cenc,URI=\"None\""
            for i in range(startNumber, math.ceil(totalDur/duration)+1):
                seg = getUrl(mpd_url, base)+prefix+str(i).zfill(zeroLen)
                #一分钟以后
                if i>60/duration:
                    m3u8_2 += "\n#EXTINF:"+str(duration)+",\n" + seg
                else:
                    m3u8_1 += "\n#EXTINF:"+str(duration)+",\n" + seg
            m3u8_1+="\n#EXT-X-ENDLIST"
            m3u8_2+="\n#EXT-X-ENDLIST"
            with open(os.path.join(output_dir, f"M3U8/未加密_audio_track_{bandwidth}.m3u8"), "w") as f1:
                f1.write(m3u8_1)
            with open(os.path.join(output_dir, f"M3U8/加密_audio_track_{bandwidth}.m3u8"), "w") as f1:
                f1.write(m3u8_2)
            #AUDIO_TRACK只留一个
            AUDIO_TRACK_1[0] = f'#EXT-X-MEDIA:TYPE=AUDIO,URI="M3U8/未加密_audio_track_{bandwidth}.m3u8",GROUP-ID="default-audio-group",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"'
            AUDIO_TRACK_2[0] = f'#EXT-X-MEDIA:TYPE=AUDIO,URI="M3U8/加密_audio_track_{bandwidth}.m3u8",GROUP-ID="default-audio-group",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"'
            

#构造两种master文件
mastre_m3u8 = "#EXTM3U\n## Generated with mpd_parser.py\n"
mastre_m3u8 += AUDIO_TRACK_1[0] + "\n"
mastre_m3u8 += "\n".join(VIDEO_TRACK_1)
with open(os.path.join(output_dir, f"未加密_0_master.m3u8"), "w", encoding="utf-8") as f1:
    f1.write(mastre_m3u8)
#加密的
mastre_m3u8 = "#EXTM3U\n## Generated with mpd_parser.py\n"
mastre_m3u8 += AUDIO_TRACK_2[0] + "\n"
mastre_m3u8 += "\n".join(VIDEO_TRACK_2)
with open(os.path.join(output_dir, f"加密_0_master.m3u8"), "w", encoding="utf-8") as f1:
    f1.write(mastre_m3u8)

#解密+合并脚本
bat_content = "@echo off\n"
bat_content += f"echo 解密视频 && mp4decrypt.exe --key {KID}:{KEY} 加密_0_master.mp4 video.mp4 && "
bat_content += f"echo 解密音频 && mp4decrypt.exe --key {KID}:{KEY} 加密_0_master(Audio).mp4 audio.mp4 && "
bat_content += "echo 转换文件 && ffmpeg -loglevel quiet -i 未加密_0_master.mp4 -i 未加密_0_master(Audio).mp4 -map 0 -map 1 -c copy temp.ts && "
bat_content += "ffmpeg -loglevel quiet -i video.mp4 -i audio.mp4 -map 0 -map 1 -c copy temp2.ts && "
bat_content += "echo 合并音视频 && ffmpeg -i concat:\"temp.ts|temp2.ts\" -map 0 -c copy MUX.mp4 && del temp.ts && del temp2.ts && del 未加密_0_master.mp4 && del 未加密_0_master(Audio).mp4 && del video.mp4 && del audio.mp4 && del 加密_0_master.mp4 && del 加密_0_master(Audio).mp4"
with open(os.path.join(output_dir, f"解密合并脚本.bat"), "w") as f1:
    f1.write(bat_content)

print("\n文件生成成功，请使用N_m3u8DL-CLI下载'未加密_0_master.m3u8'和'加密_0_master.m3u8'\n下载结束后双击'解密合并脚本.bat'即可得到成品") 
sys.exit()
```

**Comment by nilaoda** [comment]
## 更快的获取key

使用[Gooreplacer](https://github.com/jiacai2050/gooreplacer)插件，将
```
https://s3.pstatp.com/toutiao/xigua_video_web_pc/static/js/vendors~xgplayer_encrypt.77c1cd12.chunk.js
```
替换为
```
https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBPborwMAFV4DVA.bin
```

即可播放时弹出KEY：

![image](https://user-images.githubusercontent.com/20772925/75525156-4a5e5f80-5a4a-11ea-8d84-dbbf3bb08777.png)

**Comment by qupig** [comment]
https://s3.pstatp.com/toutiao/xigua_video_web_pc/static/js/vendors~xgplayer_encrypt.217ffcd8.chunk.js

window换成this了，不好直接调用了

**Comment by nilaoda** [comment]
> https://s3.pstatp.com/toutiao/xigua_video_web_pc/static/js/vendors~xgplayer_encrypt.217ffcd8.chunk.js
> 
> window换成this了，不好直接调用了

新搞了一个，现在基本上用不着解析MPD了

把
```
https://s3.pstatp.com/toutiao/xigua_video_web_pc/static/js/vendors~xgplayer_encrypt..*?.chunk.js
```
替换成
```
https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBI7cKQIAFpQDzQ.bin
```

就可以了：

![image](https://user-images.githubusercontent.com/20772925/79069642-60766580-7d02-11ea-92a6-bb3c386165cc.png)

然后解密用KID和KEY就行

**Comment by hihaozhe** [comment]
部分视频可以，部分视频不可以
https://www.ixigua.com/cinema/album/86HGMQqGggu/?logTag=tRGFIRX2beyVOOdt3Jwes

**Comment by nilaoda** [comment]
> 部分视频可以，部分视频不可以
> https://www.ixigua.com/cinema/album/86HGMQqGggu/?logTag=tRGFIRX2beyVOOdt3Jwes

看了一下，这种视频是旧版的MPD分段，和教程上面的流程一样。我写了一个js，帮助实现这个流程：
把
```
https://s3.pstatp.com/toutiao/xigua_video_web_pc/static/js/vendors~xgplayer_encrypt..*?.chunk.js
```
替换成
```
https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBI7cKQIAFpQDzQ.bin
```
就可以了：

![image](https://user-images.githubusercontent.com/20772925/79074296-287d1b80-7d1e-11ea-8405-62176c2c4b14.png)


使用[N_m3u8DL-CLI](https://github.com/nilaoda/N_m3u8DL-CLI)下载完成四个文件后`(理论上为两个mp4, 一个m4a, 一个aac)`，在同名目录执行生成的**解密合并命令**即可得到成片

![image](https://user-images.githubusercontent.com/20772925/79074286-1ef3b380-7d1e-11ea-9191-2781cfff8457.png)

**Comment by nilaoda** [comment]
### 更新JS。支持分段和整段两种
---
把
```
https://s3.pstatp.com/toutiao/xigua_video_web_pc/static/js/vendors~xgplayer_encrypt..*?.chunk.js
```
替换成
```
https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBI68twMAFoYDrA.bin
```
就可以了：

整段效果:
![image](https://user-images.githubusercontent.com/20772925/79094627-bb539f80-7d8a-11ea-80fd-8a733c9fe770.png)

分段效果:
![image](https://user-images.githubusercontent.com/20772925/79094643-c3134400-7d8a-11ea-867e-8f5a0a0abf5e.png)

整段直接下载解密合并就行了，分段的下载好m3u8文件后用[N_m3u8DL-CLI](https://github.com/nilaoda/N_m3u8DL-CLI)下载完成`(理论上为一个mp4, 一个aac)`，在同名目录执行生成的**解密合并命令**即可得到成片

**Comment by hihaozhe** [comment]
很方便了，Thanks♪(･ω･)ﾉ

nilaoda <notifications@github.com> 于2020年4月13日周一 下午1:32写道：

**Comment by qupig** [comment]
https://github.com/nilaoda/Blog/issues/17#issuecomment-612757982  @nilaoda 
似乎不能这样通配替换，会导致别的加载不出来，初测似乎每个UP主的脚本都不通用。

**Comment by toorich** [comment]
> > 仅技术讨论学习，请勿用于非法用途
> 
> 以`https://www.ixigua.com/cinema/album/85dS526nogC/?logTag=epq5lhhbOxZskD-YlXjwY`为例：
> 
> ## 获得KEY
> 过滤`play_licenses`，复制出对应的`KID`和`加密key`备用
> 
> ![image](https://user-images.githubusercontent.com/20772925/75517967-e2544d00-5a3a-11ea-89b9-74b63b648cd2.png)
> 
> 在`console`中执行脚本，来源[点我](https://s3.pstatp.com/toutiao/xigua_video_web_pc/static/js/vendors~xgplayer_encrypt.b05f677a.chunk.js)
> 
> ```js
> function str2hex (e) {
>  if ("" === e)
>         return "";
>     for (var t = [], r = 0; r < e.length; r++)
>         t.push(e.charCodeAt(r));
>     return t
> }
> 
> var tt1 = window.atob("m+ZPqQW2SvxrsnGpOucmxjjkGqsAt03+VOMZ/lLlGvJQ0EqoqA==");
> var tt2 = str2hex(tt1);
> var tt3 = window.Module._malloc(Number(tt2.length));
> window.Module.HEAP8.set(tt2, tt3);
> var p = window.Module._openBox(Number(tt3), tt2.length);
> var f = window.Module.UTF8ToString(p);
> console.log(f);
> ```
> 
> ![image](https://user-images.githubusercontent.com/20772925/75518050-0ca60a80-5a3b-11ea-8e5c-ddf7a826079f.png)
> 
> ## 下载分片
> 具体链接构造格式可以结合抓包和MPD文件观察
> 
> `mpd`文件中有详细的码率信息即分片信息：
> 
> ![image](https://user-images.githubusercontent.com/20772925/73357575-98f7cd00-42d7-11ea-93e7-34faf9f0a4a3.png)
> 
> ## 解密过程
> 前`1分钟`**没加密**，直接下载合并即可
> 
> `1分钟`之后的解密方式：
> 
> 将`1_init`与后面所有分片**二进制合并**为`test.mp4`，用上面的`KID`和`解密好的KEY`开始进行解密
> 
> ```
> mp4decrypt.exe --key 5e306e5dc8d2ea26b24e3bfe0002043b:0ea5fa9d12ce49789f23ea24e5d3a0d8 test.mp4 2.mp4
> ```
> 
> 最后合并即可：
> 
> ```
> ffmpeg -i concat:"1.mp4|2.mp4" -c copy "final.mp4"
> ```
> 
> ![image](https://user-images.githubusercontent.com/20772925/73362098-2b509e80-42e1-11ea-9215-21d7fb794993.png)
> 
> 音频同理
> 
> 附：
> http://zebulon.bok.net/Bento4/binaries/Bento4-SDK-1-5-1-629.x86-microsoft-win32-vs2010.zip

有的视频在play_licenses段不会返回密钥，如https://www.ixigua.com/6785164824050401799/
