### ISSUE TITLE
【教程】优酷cmaf格式DRM手动解密

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/Blog#19]
---
>  仅技术讨论学习，请勿用于非法用途
---

例如：https://v.youku.com/v_show/id_XNDM1Nzg4MzQ4MA==.html

使用[js](https://nilaoda.github.io/N_m3u8DL-CLI/GetM3u8.html)获取的`m3u8`中，`type`为`cmaf4hd3`

```
http://pl-ali.youku.com/playlist/m3u8?vid=XNDM1Nzg4MzQ4MA%3D%3D&type=cmaf4hd3&...
```

观察可知，`m3u8`中有音频和视频两个轨道

然后音频和视频两个`m3u8`中，又分别包含`map`文件

需要做的就是将两个`m3u8`中的文件(包括`map`)都下载下来，然后使用`copy /b`将它们合并  
（该过程在 [N_m3u8DL-CLI](https://github.com/nilaoda/N_m3u8DL-CLI) v2.5.0及以后的版本中将被自动处理）：

![image](https://user-images.githubusercontent.com/20772925/75103535-bac64480-5636-11ea-990e-501a8e4ea4f7.png)

---

解密过程：

**获取 key**
在浏览器播放页面执行以下js代码 [[ref](https://stackoverflow.com/questions/40031688/javascript-arraybuffer-to-hex)]：
 ```js
javascript:var a=prompt("key",Array.prototype.map.call(_drmKey3, n => ("00" + n.toString(16)).slice(-2)).join(""));
 ```

![image](https://user-images.githubusercontent.com/20772925/75103602-c9612b80-5637-11ea-8530-fdfdc56a54fd.png)

复制留存备用

**获取视频文件KID**
在视频目录执行以下命令
```
> mp4dump.exe "蜘蛛侠：英雄远征_02.06.51.mp4" | find /I "default_KID"
                    default_KID = [33 41 90 a8 5a 5e 8d 0a 72 ab b9 53 08 cc 0f e5]
```
则`KID`为`33 41 90 a8 5a 5e 8d 0a 72 ab b9 53 08 cc 0f e5`

**解密视频**
```
> mp4decrypt.exe --show-progress --key 334190a85a5e8d0a72abb95308cc0fe5:b70c5f126704b3d29cccbc87a800d1d7  "蜘蛛侠：英雄远征_02.06.51.mp4" video.mp4
```

**解密音频**
```
> mp4decrypt.exe --show-progress --key 334190a85a5e8d0a72abb95308cc0fe5:b70c5f126704b3d29cccbc87a800d1d7  "蜘蛛侠：英雄远征_02.06.51(Audio).mp4" audio.mp4
```

**混流**
```
> ffmpeg -i video.mp4 -i audio.mp4 -map 0 -map 1 -c copy mux.mp4
```

![image](https://user-images.githubusercontent.com/20772925/75103659-a6834700-5638-11ea-9758-a62553dc3e11.png)

附：
http://zebulon.bok.net/Bento4/binaries/Bento4-SDK-1-5-1-629.x86-microsoft-win32-vs2010.zip

**Comment by ownerowner** [comment]
想问一下发现优酷m3u8文件里如今没有aes加密信息，也没有key值，但是视频确实是经过加密的。通过js已经获取了key值了。想先下载合并加密的ts至本地，然后再用key解密。ffmpeg相关命令行不知楼主能不能告知，谢谢

**Comment by nilaoda** [comment]
> 想问一下发现优酷m3u8文件里如今没有aes加密信息，也没有key值，但是视频确实是经过加密的。通过js已经获取了key值了。想先下载合并加密的ts至本地，然后再用key解密。ffmpeg相关命令行不知楼主能不能告知，谢谢

ffmpeg不支持

**Comment by ownerowner** [comment]
你好，这个我通过js解析到key值，但是通过软件下载视频显示无法解析，然后自动弹出关闭。视频链接地址如下，这个应该是普通drm加密，希望您帮忙处理一下https://v.youku.com/v_show/id_XNDM4MDQyODI3Mg==.html

**Comment by nilaoda** [comment]
> 你好，这个我通过js解析到key值，但是通过软件下载视频显示无法解析，然后自动弹出关闭。视频链接地址如下，这个应该是普通drm加密，希望您帮忙处理一下。1080p视频加了密，其他清晰度未加密。https://v.youku.com/v_show/id_XNDM4MDQyODI3Mg==.html

经过测试，能够正常下载：
```
N_m3u8DL-CLI.exe "https://valipl-vip.cp31.ott.cibntv.net/..." --saveName "暴风新娘 05_46.40" --stopSpeed "500" --useKeyBase64 "C9tp0kUMQufXHFnJ8fDBOQ==" --enableDelAfterDone --disableDateInfo --noProxy --enableYouKuAes 
```

**Comment by ownerowner** [comment]
> > 你好，这个我通过js解析到key值，但是通过软件下载视频显示无法解析，然后自动弹出关闭。视频链接地址如下，这个应该是普通drm加密，希望您帮忙处理一下。1080p视频加了密，其他清晰度未加密。https://v.youku.com/v_show/id_XNDM4MDQyODI3Mg==.html
> 
> 经过测试，能够正常下载：
> 
> ```
> N_m3u8DL-CLI.exe "https://valipl-vip.cp31.ott.cibntv.net/..." --saveName "暴风新娘 05_46.40" --stopSpeed "500" --useKeyBase64 "C9tp0kUMQufXHFnJ8fDBOQ==" --enableDelAfterDone --disableDateInfo --noProxy --enableYouKuAes 
> ```

感谢大佬指正，经测试，下载不了原因是没有使用cmd调用ffmpeg下载文件，直接使用下载器下载会出现闪退现象，目前已经解决，麻烦您能将base64 解密js发我邮箱吗，因为之前没来得及保存。mail:sunbetty812@gmail.com

**Comment by 1952540453** [comment]
你好，复仇者联盟2 我按照步骤进行解密，然后只有前1分40秒才会正常解密，后面的就是花屏，无法正常播放

**Comment by 1952540453** [comment]
大佬 能帮忙分析一下什么问题么？这一部片子，无法完整解密：https://v.youku.com/v_show/id_XMTMzNjQ2NTMwNA==.html?spm=a2h0k.11417342.soresults.dplaybutton&lang=%E8%8B%B1%E8%AF%AD

**Comment by nilaoda** [comment]
> 大佬 能帮忙分析一下什么问题么？这一部片子，无法完整解密：https://v.youku.com/v_show/id_XMTMzNjQ2NTMwNA==.html?spm=a2h0k.11417342.soresults.dplaybutton&lang=%E8%8B%B1%E8%AF%AD

应该是你网络不好导致下载丢包了，我试了一下正常解密，没什么问题

**Comment by zywhb** [comment]
老大，https://v.youku.com/v_show/id_XNDUxNjgxMDMyMA==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!4~5~5~5~A
m3u8地址：http://valipl-vip.cp31.ott.cibntv.net/677339549944471C1C31533DD/05004A00005E65FABC8BB7800000003E898E7C-21EF-41C0-8988-72992B1E7048-1-65404.m3u8?ccode=0502&duration=2611&expire=18000&psid=9256c4f28cc213e77d5e74e4a07fe49a&ups_client_netip=1b1befc6&ups_ts=1583763889&ups_userid=830760056&utid=mwmWFtz%2FElUCARsb65DRUm8Q&vid=XNDUxNjgxMDMyMA&vkey=B09606d8f11a6f9ce501ac5cfa89a9822&sm=1&operate_type=1&dre=u38&si=78&eo=0&dst=1&iv=1&s=c88ac4a7efbfbd4911ef&bc=2
KEY值为：JXYYk1c1RAEszFuHIilARQ==
使用N_m3u8DL-CLI2.57下载不了，在最后合并时闪退，应该解密有误

**Comment by nilaoda** [comment]
> 老大，https://v.youku.com/v_show/id_XNDUxNjgxMDMyMA==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!4~5~5~5~A
> m3u8地址：http://valipl-vip.cp31.ott.cibntv.net/677339549944471C1C31533DD/05004A00005E65FABC8BB7800000003E898E7C-21EF-41C0-8988-72992B1E7048-1-65404.m3u8?ccode=0502&duration=2611&expire=18000&psid=9256c4f28cc213e77d5e74e4a07fe49a&ups_client_netip=1b1befc6&ups_ts=1583763889&ups_userid=830760056&utid=mwmWFtz%2FElUCARsb65DRUm8Q&vid=XNDUxNjgxMDMyMA&vkey=B09606d8f11a6f9ce501ac5cfa89a9822&sm=1&operate_type=1&dre=u38&si=78&eo=0&dst=1&iv=1&s=c88ac4a7efbfbd4911ef&bc=2
> KEY值为：JXYYk1c1RAEszFuHIilARQ==
> 使用N_m3u8DL-CLI2.57下载不了，在最后合并时闪退，应该解密有误

KEY为`XsGyxaLAXgdLmpNxV2v/bQ==`

**Comment by zywhb** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nilaoda"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 凌晨0:21
收件人:&nbsp;"nilaoda/Blog"<Blog@noreply.github.com&gt;;
抄送:&nbsp;"飞龙科技"<649292376@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19)



 
老大，https://v.youku.com/v_show/id_XNDUxNjgxMDMyMA==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!4~5~5~5~A
 m3u8地址：http://valipl-vip.cp31.ott.cibntv.net/677339549944471C1C31533DD/05004A00005E65FABC8BB7800000003E898E7C-21EF-41C0-8988-72992B1E7048-1-65404.m3u8?ccode=0502&amp;duration=2611&amp;expire=18000&amp;psid=9256c4f28cc213e77d5e74e4a07fe49a&amp;ups_client_netip=1b1befc6&amp;ups_ts=1583763889&amp;ups_userid=830760056&amp;utid=mwmWFtz%2FElUCARsb65DRUm8Q&amp;vid=XNDUxNjgxMDMyMA&amp;vkey=B09606d8f11a6f9ce501ac5cfa89a9822&amp;sm=1&amp;operate_type=1&amp;dre=u38&amp;si=78&amp;eo=0&amp;dst=1&amp;iv=1&amp;s=c88ac4a7efbfbd4911ef&amp;bc=2
 KEY值为：JXYYk1c1RAEszFuHIilARQ==
 使用N_m3u8DL-CLI2.57下载不了，在最后合并时闪退，应该解密有误
  
KEY为XsGyxaLAXgdLmpNxV2v/bQ==
 
老大，用的你的key&nbsp; js脚本：javascript:var a=prompt(videoPlayer.getData()._videoData.title + "key", btoa(String.fromCharCode.apply(null, ____hexA)));

m3u8 js脚本：javascript:var url;var size=0;Array.from(videoPlayer.getData()._playlistData.stream).forEach(function(element,index,array){if(element.audio_lang==videoPlayer.getConfig().language&amp;&amp;element.size&gt;size){url=element.m3u8_url;size=element.size}});/*nilaoda*/prompt(videoPlayer.getData()._videoData.title+"_"+videoPlayer.getConfig().language+"_"+(size/1024/1024).toFixed(2)+"MB",url);

m3u8地址和key&nbsp;写入gui中，还是解密不了，烦请有时间帮忙测试一下(前天还可以解密)：

片源地址为：https://v.youku.com/v_show/id_XNDUxNjgxMDMyMA==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!4~5~5~5~A

**Comment by nilaoda** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"nilaoda"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月10日(星期二) 凌晨0:21 收件人:&nbsp;"nilaoda/Blog"<Blog@noreply.github.com&gt;; 抄送:&nbsp;"飞龙科技"<649292376@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19) 老大，https://v.youku.com/v_show/id_XNDUxNjgxMDMyMA==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!4~5~5~5~A m3u8地址：http://valipl-vip.cp31.ott.cibntv.net/677339549944471C1C31533DD/05004A00005E65FABC8BB7800000003E898E7C-21EF-41C0-8988-72992B1E7048-1-65404.m3u8?ccode=0502&amp;duration=2611&amp;expire=18000&amp;psid=9256c4f28cc213e77d5e74e4a07fe49a&amp;ups_client_netip=1b1befc6&amp;ups_ts=1583763889&amp;ups_userid=830760056&amp;utid=mwmWFtz%2FElUCARsb65DRUm8Q&amp;vid=XNDUxNjgxMDMyMA&amp;vkey=B09606d8f11a6f9ce501ac5cfa89a9822&amp;sm=1&amp;operate_type=1&amp;dre=u38&amp;si=78&amp;eo=0&amp;dst=1&amp;iv=1&amp;s=c88ac4a7efbfbd4911ef&amp;bc=2 KEY值为：JXYYk1c1RAEszFuHIilARQ== 使用N_m3u8DL-CLI2.57下载不了，在最后合并时闪退，应该解密有误 KEY为XsGyxaLAXgdLmpNxV2v/bQ== 老大，用的你的key&nbsp; js脚本：javascript:var a=prompt(videoPlayer.getData()._videoData.title + "key", btoa(String.fromCharCode.apply(null, ____hexA))); m3u8 js脚本：javascript:var url;var size=0;Array.from(videoPlayer.getData()._playlistData.stream).forEach(function(element,index,array){if(element.audio_lang==videoPlayer.getConfig().language&amp;&amp;element.size&gt;size){url=element.m3u8_url;size=element.size}});/*nilaoda*/prompt(videoPlayer.getData()._videoData.title+"_"+videoPlayer.getConfig().language+"_"+(size/1024/1024).toFixed(2)+"MB",url); m3u8地址和key&nbsp;写入gui中，还是解密不了，烦请有时间帮忙测试一下(前天还可以解密)： 片源地址为：https://v.youku.com/v_show/id_XNDUxNjgxMDMyMA==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!4~5~5~5~A You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

优酷对js做了修改，使用旧版player的js获取的key能够正常解密

**Comment by zywhb** [comment]
nilaoda 有新版的js吗?老大真是太伟大了，这么快都回复了

**Comment by 1952540453** [comment]
大佬 您好，旧版的player,在哪可以弄到，应该和浏览器没有关系的是么

**Comment by zywhb** [comment]
实际上是drm的那个key修改了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "1952540453"<notifications@github.com&gt;; 
发送时间: 2020年3月10日(星期二) 中午11:42
收件人: "nilaoda/Blog"<Blog@noreply.github.com&gt;; 
抄送: "飞龙科技"<649292376@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19)




大佬 您好，旧版的player,在哪可以弄到，应该和浏览器没有关系的是么

**Comment by 1952540453** [comment]
您好 我这个cmaf 加密的内容， 我每次下载的时候都会出现一个目录，cmaf手动解密无法全部解密；链接https://v.youku.com/v_show/id_XMTMzNjQ2NTMwNA==.html?spm=a2h0k.11417342.soresults.dplaybutton&lang=%E8%8B%B1%E8%AF%AD，大佬能帮忙分析一下么，cmaf这个获取密码的方式也变了么

**Comment by nilaoda** [comment]
统一回复，新建规则，将
```
https://g.alicdn.com/player/beta-ykplayer/.*?/youku-player.min.js
```
替换为
```
https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBHb9Ow0AFxMEPg.bin
```

**Comment by zywhb** [comment]
收到，可以了，谢谢老大！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nilaoda"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 中午12:20
收件人:&nbsp;"nilaoda/Blog"<Blog@noreply.github.com&gt;;
抄送:&nbsp;"飞龙科技"<649292376@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19)




统一回复，新建规则，将
 https://g.alicdn.com/player/beta-ykplayer/.*?/youku-player.min.js  
替换为
 https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBHb9Ow0AFxMEPg.bin

**Comment by 1952540453** [comment]
您好 这种只是针对普通的加密吧，应该不是cmaf加密方式，是么





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zywhb"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 中午12:26
收件人:&nbsp;"nilaoda/Blog"<Blog@noreply.github.com&gt;;
抄送:&nbsp;"yfy"<1952540453@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19)



收到，可以了，谢谢老大！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"nilaoda"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月10日(星期二) 中午12:20 
 收件人:&amp;nbsp;"nilaoda/Blog"<Blog@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"飞龙科技"<649292376@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19) 
 
 
 
 
 统一回复，新建规则，将 
  https://g.alicdn.com/player/beta-ykplayer/.*?/youku-player.min.js   
 替换为 
  https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBHb9Ow0AFxMEPg.bin

**Comment by nilaoda** [comment]
> 您好 我这个cmaf 加密的内容， 我每次下载的时候都会出现一个目录，cmaf手动解密无法全部解密；链接[https://v.youku.com/v_show/id_XMTMzNjQ2NTMwNA==.html?spm=a2h0k.11417342.soresults.dplaybutton&lang=%E8%8B%B1%E8%AF%AD，大佬能帮忙分析一下么，cmaf这个获取密码的方式也变了么](https://v.youku.com/v_show/id_XMTMzNjQ2NTMwNA==.html?spm=a2h0k.11417342.soresults.dplaybutton&lang=%E8%8B%B1%E8%AF%AD%EF%BC%8C%E5%A4%A7%E4%BD%AC%E8%83%BD%E5%B8%AE%E5%BF%99%E5%88%86%E6%9E%90%E4%B8%80%E4%B8%8B%E4%B9%88%EF%BC%8Ccmaf%E8%BF%99%E4%B8%AA%E8%8E%B7%E5%8F%96%E5%AF%86%E7%A0%81%E7%9A%84%E6%96%B9%E5%BC%8F%E4%B9%9F%E5%8F%98%E4%BA%86%E4%B9%88)

`f3adfc1a249ace4e9783a1778e213350`这个key

**Comment by zywhb** [comment]
我测试了，没问题啊mp4decrypt.exe --show-progress --key 3fe6bbe6ada36b2e228bfe30f5ffdb52:f3adfc1a249ace4e9783a1778e213350&nbsp; "video.mp4" video_ok.mp4
mp4decrypt.exe --show-progress --key 3fe6bbe6ada36b2e228bfe30f5ffdb52:f3adfc1a249ace4e9783a1778e213350&nbsp; "audio.mp4" audio_ok.mp4




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nilaoda"<notifications@github.com&gt;; 
发送时间: 2020年3月10日(星期二) 中午1:28
收件人: "nilaoda/Blog"<Blog@noreply.github.com&gt;; 
抄送: "飞龙科技"<649292376@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19)



 
您好 我这个cmaf 加密的内容， 我每次下载的时候都会出现一个目录，cmaf手动解密无法全部解密；链接https://v.youku.com/v_show/id_XMTMzNjQ2NTMwNA==.html?spm=a2h0k.11417342.soresults.dplaybutton&amp;lang=%E8%8B%B1%E8%AF%AD，大佬能帮忙分析一下么，cmaf这个获取密码的方式也变了么
  
f3adfc1a249ace4e9783a1778e213350这个key

**Comment by 1952540453** [comment]
好的谢谢了&nbsp; 将重定向那个配置后，从老播放器里拿出来解密的密码 就可以了，昨天不行





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zywhb"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 中午1:46
收件人:&nbsp;"nilaoda/Blog"<Blog@noreply.github.com&gt;;
抄送:&nbsp;"yfy"<1952540453@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19)



我测试了，没问题啊mp4decrypt.exe --show-progress --key 3fe6bbe6ada36b2e228bfe30f5ffdb52:f3adfc1a249ace4e9783a1778e213350&amp;nbsp; "video.mp4" video_ok.mp4 
 mp4decrypt.exe --show-progress --key 3fe6bbe6ada36b2e228bfe30f5ffdb52:f3adfc1a249ace4e9783a1778e213350&amp;nbsp; "audio.mp4" audio_ok.mp4 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "nilaoda"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月10日(星期二) 中午1:28 
 收件人: "nilaoda/Blog"<Blog@noreply.github.com&amp;gt;;  
 抄送: "飞龙科技"<649292376@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19) 
 
 
 
   
 您好 我这个cmaf 加密的内容， 我每次下载的时候都会出现一个目录，cmaf手动解密无法全部解密；链接https://v.youku.com/v_show/id_XMTMzNjQ2NTMwNA==.html?spm=a2h0k.11417342.soresults.dplaybutton&amp;amp;lang=%E8%8B%B1%E8%AF%AD，大佬能帮忙分析一下么，cmaf这个获取密码的方式也变了么 
    
 f3adfc1a249ace4e9783a1778e213350这个key

**Comment by ysbyf1** [comment]
请问这一视频该如何下载呢：https://v.youku.com/v_show/id_XNDQ5NjUyNDI3Ng==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!15~5~5~5~A，每次刷新播放获取的key值是不一样的，下载后合并不成功，应该是解密的问题

**Comment by zywhb** [comment]
nilaoda 重定向不行了，取不key了
https://v.youku.com/v_show/id_XNDUxNDQ4MDQyOA==.html?spm=a2hbt.13141534.app.5~5!2~5!2~5~5~5!2~5~5!2~5!2~5!2~5~A!24

**Comment by nilaoda** [comment]
> 请问这一视频该如何下载呢：[https://v.youku.com/v_show/id_XNDQ5NjUyNDI3Ng==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!15~5~5~5~A，每次刷新播放获取的key值是不一样的，下载后合并不成功，应该是解密的问题](https://v.youku.com/v_show/id_XNDQ5NjUyNDI3Ng==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!15~5~5~5~A%EF%BC%8C%E6%AF%8F%E6%AC%A1%E5%88%B7%E6%96%B0%E6%92%AD%E6%94%BE%E8%8E%B7%E5%8F%96%E7%9A%84key%E5%80%BC%E6%98%AF%E4%B8%8D%E4%B8%80%E6%A0%B7%E7%9A%84%EF%BC%8C%E4%B8%8B%E8%BD%BD%E5%90%8E%E5%90%88%E5%B9%B6%E4%B8%8D%E6%88%90%E5%8A%9F%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF%E8%A7%A3%E5%AF%86%E7%9A%84%E9%97%AE%E9%A2%98)

KEY为`7ofcR2xxrUX3G4LgCnwXxA==`

**Comment by nilaoda** [comment]
> nilaoda 重定向不行了，取不key了
> https://v.youku.com/v_show/id_XNDUxNDQ4MDQyOA==.html?spm=a2hbt.13141534.app.5~5!2~5!2~5~5~5!2~5~5!2~5!2~5!2~5~A!24

不是优酷自己的copyrightDRM了，采用了widevine

**Comment by zywhb** [comment]
m3u8:http://valipl-vip.cp31.ott.cibntv.net/697450F07AA327148F5A12B87/05004A00005E673DFE8BB780000000221A1B67-C481-4A5C-8A08-52C1CFAEC5A3-1-114.m3u8?ccode=0502&amp;duration=4609&amp;expire=18000&amp;psid=c6636df863f76e26e79d2fd5c3a88d6d&amp;ups_client_netip=1b1befc6&amp;ups_ts=1583903753&amp;ups_userid=830760056&amp;utid=mwmWFtz%2FElUCARsb65DRUm8Q&amp;vid=XNDQ5NjUyNDI3Ng&amp;vkey=Bea2a6705b727753953b07a9e88507e51&amp;sm=1&amp;operate_type=1&amp;dre=u38&amp;si=78&amp;eo=0&amp;dst=1&amp;iv=1&amp;s=46efbfbd591c0cefbfbd&amp;bc=2
key:7ofcR2xxrUX3G4LgCnwXxA==
用的cli2.57&nbsp;下载解密正常


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nilaoda"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午1:15
收件人:&nbsp;"nilaoda/Blog"<Blog@noreply.github.com&gt;;
抄送:&nbsp;"飞龙科技"<649292376@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19)



 
请问这一视频该如何下载呢：https://v.youku.com/v_show/id_XNDQ5NjUyNDI3Ng==.html?spm=a2hcb.12701310.app.55!25!3555!15555~A，每次刷新播放获取的key值是不一样的，下载后合并不成功，应该是解密的问题
  
KEY为7ofcR2xxrUX3G4LgCnwXxA==

**Comment by zywhb** [comment]
nilaoda widevine有解吗

**Comment by nilaoda** [comment]
> nilaoda widevine有解吗

对我们来说几乎无解，对大佬来说小菜一碟

**Comment by zywhb** [comment]
哈哈，你都是我们心目中的大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nilaoda"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午1:29
收件人:&nbsp;"nilaoda/Blog"<Blog@noreply.github.com&gt;;
抄送:&nbsp;"飞龙科技"<649292376@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/Blog] 【教程】优酷cmaf格式DRM手动解密 (#19)



 
nilaoda widevine有解吗
  
对我们来说几乎无解，对大佬来说小菜一碟

**Comment by ysbyf1** [comment]
> > 请问这一视频该如何下载呢：[https://v.youku.com/v_show/id_XNDQ5NjUyNDI3Ng==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!15~5~5~5~A，每次刷新播放获取的key值是不一样的，下载后合并不成功，应该是解密的问题](https://v.youku.com/v_show/id_XNDQ5NjUyNDI3Ng==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!15~5~5~5~A%EF%BC%8C%E6%AF%8F%E6%AC%A1%E5%88%B7%E6%96%B0%E6%92%AD%E6%94%BE%E8%8E%B7%E5%8F%96%E7%9A%84key%E5%80%BC%E6%98%AF%E4%B8%8D%E4%B8%80%E6%A0%B7%E7%9A%84%EF%BC%8C%E4%B8%8B%E8%BD%BD%E5%90%8E%E5%90%88%E5%B9%B6%E4%B8%8D%E6%88%90%E5%8A%9F%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF%E8%A7%A3%E5%AF%86%E7%9A%84%E9%97%AE%E9%A2%98)
> 
> KEY为`7ofcR2xxrUX3G4LgCnwXxA==` 正常解密

感谢大佬，确实可以了，但是这个key值是怎么获取到的呢，用原来的js代码好像行不通了，原来获取的key值方法获取出来的是动态的，每次的都不一样
