### ISSUE TITLE
【工具】Wetv批量解析工具

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/Blog#28]
---
>  仅技术讨论学习，请勿用于非法用途
---

使用方法：程序界面输入vid或直接在命令行中输入`(Wetv.exe vid1,vid,...)`。多个vid使用`,`隔开

![image](https://user-images.githubusercontent.com/20772925/85964551-9a473600-b9ec-11ea-9074-a8cc8089b407.png)

![image](https://user-images.githubusercontent.com/20772925/85964558-a0d5ad80-b9ec-11ea-818e-60b3e3c761c3.png)

PS：程序会自动读取同目录下的`cookie.txt`作为请求头。

---

2020年6月29日第一版：[Wetv_20200629.zip](https://github.com/nilaoda/Blog/files/4843388/Wetv_20200629.zip)

**Comment by nilaoda** [comment]
* 更新，支持单个cid解析全集：

    输入`cid=xxx`即可

    ![image](https://user-images.githubusercontent.com/20772925/86023576-702e5c00-ba5e-11ea-9806-e57e1613dd1b.png)

* 双击运行情况下，程序解析程序后不会自动退出。

---

2020年6月29日第二版：[Wetv_20200629(ver2).zip](https://github.com/nilaoda/Blog/files/4846418/Wetv_20200629.ver2.zip)

**Comment by bmw1398** [comment]
大佬，现在有个问题，WETV上没有字幕的视频（比如说泰剧），用这个工具提取不了，会出错。

**Comment by nilaoda** [comment]
* 修复无字幕视频下载报错问题

---

2020年6月30日第一版：[Wetv_20200630.zip](https://github.com/nilaoda/Blog/files/4849684/Wetv_20200630.zip)

**Comment by bmw1398** [comment]
谢谢大佬，无字幕的现在也可以下载了，完美！

**Comment by zackmark29** [comment]
How to use for this link?
https://wetv.vip/en/play/tfzx5m7vesn1tjv/h0031r1kfm1
Always exited when entering that link

**Comment by nilaoda** [comment]
> h0031r1kfm1

input `h0031r1kfm1`

**Comment by zackmark29** [comment]
Wow amazing it worked. thank you so much

**Comment by zackmark29** [comment]
I only got all chinese version. How I can just select english version?

**Comment by nilaoda** [comment]
> How I can get automatically the English File name? and only .m3u8 and English subtitle?

Just for chinese now.

**Comment by zackmark29** [comment]
> > How I can get automatically the English File name? and only .m3u8 and English subtitle?
> 
> Just for chinese now.

AH alright. I'll just gonna wait :)
I'm a big fan of you Nilaoda. You inspired me to learn C# :). I only learned from your codes 
I followed some of your blogs and github as well.

**Comment by sanshicangliang** [comment]
@nilaoda  大佬，云视听TV那个抓真4K高码，还行么。

**Comment by dcln78** [comment]
@nilaoda 大佬,优酷获取cmaf key的JS书签失效了啊 有木有更新的呀

**Comment by wyl5602443** [comment]
解析了以后怎么下载？？？我输入了vid之后这个解析结果到是出来了，但下面就是显示，按任意键退出！也没有下载选项啊，看了一下目录，文件倒是出现了，但没有下载下来啊，M3U8文件一直只有几十KB！没搞懂......

**Comment by nilaoda** [comment]
> 解析了以后怎么下载？？？我输入了vid之后这个解析结果到是出来了，但下面就是显示，按任意键退出！也没有下载选项啊，看了一下目录，文件倒是出现了，但没有下载下来啊，M3U8文件一直只有几十KB！没搞懂......
> 噢，知道了，要将下载的M3U8文件拖入M3U8下载器中，就下载了。
> 能解析出WeTV的4K源么？？？

不能。而且现在wetv新剧已经不会有4K了

**Comment by bmw1398** [comment]
大佬，能帮忙看下泰剧《天才枪手》花絮里有三个有中字的视频解析不了，c00345vm5f9,l0034q0b6j4,i0034j16iiy会提示：您所在的地区因版权原因无法播放，去看看其他影片吧 。我已经是泰线全局了，其他的泰剧正剧花絮（含有中字的）都正常，就这三个出错。
谢谢

**Comment by bmw1398** [comment]
大佬，WETV上发现有二个视频M3U8解析后转到下载器去解析会提示出错，能帮忙看下吗？穿越火线的24/26二集
https://wetv.vip/zh-cn/play/mkrdnvmefgqck80-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF/k0034zagbaa-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF_24
https://wetv.vip/zh-cn/play/mkrdnvmefgqck80-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF/c00346qmqdj-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF_26
出错信息：不支持SAMPLE-AES-CTR加密方式，将不被处理，且强制开启二进制合并
写出meta.json文件时长：52m00s总分片：390，已选择分片：390开始下载文件
下载MAP文件.
读取文件信息.
PID NULL:Video h264（avcl/0x31637661），none，1920x1080，25k tbr，25k tbn，50k tbc（default）
文件下载下来是花屏
这是新加密吗？能帮忙看看吗？谢谢

**Comment by nilaoda** [comment]
> 大佬，WETV上发现有二个视频M3U8解析后转到下载器去解析会提示出错，能帮忙看下吗？穿越火线的24/26二集
> https://wetv.vip/zh-cn/play/mkrdnvmefgqck80-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF/k0034zagbaa-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF_24
> https://wetv.vip/zh-cn/play/mkrdnvmefgqck80-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF/c00346qmqdj-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF_26
> 出错信息：不支持SAMPLE-AES-CTR加密方式，将不被处理，且强制开启二进制合并
> 写出meta.json文件时长：52m00s总分片：390，已选择分片：390开始下载文件
> 下载MAP文件.
> 读取文件信息.
> PID NULL:Video h264（avcl/0x31637661），none，1920x1080，25k tbr，25k tbn，50k tbc（default）
> 文件下载下来是花屏
> 这是新加密吗？能帮忙看看吗？谢谢

超前点播？应该是加密了。本软件不支持。

**Comment by bmw1398** [comment]
不是超前点播，超前点播的，WETV.EXE是解析不出M3U8的，只是正常的VIP剧集，在线可以看全整集的，然后wetv.exe可以解析的，解析出来的名称是穿越火线_24_320181.m3u8，穿越火线_26_320181.m3u8 ，原来的都是321004才可以下载，比如穿越火线_25_321004.m3u8。
嘿，要么就是WETV也开始加密了，要么就是超前释放出来后，他们参数没改好。

**Comment by bmw1398** [comment]
补充下：24 26 27字幕WETV.EXE可以正常下载

**Comment by NaufalAriqS21** [comment]
Hello, any clue how to get "&cKey" in url request?

**Comment by zackmark29** [comment]
> Hello, any clue how to get "&cKey" in url request?

That's also what I want to know. I just reviewing the json link and that's the main needed the "cKey"

@nilaoda  could you tell us how can we get it manually? so that I can access this json url

https://play.wetv.vip/getvinfo?&charge=0&defaultfmt=auto&otype=json&platform=4830201&appVer=3.5.57&ehost=https%3A%2F%2Fwetv.vip%2Fen%2Fplay%2Fcgfkq06fo3sdbgr-Midsummer%2520is%2520Full%2520of%2520Love%2Fs00343f4k3v-Highlight%2520EP2%2520Ver.%25202%2520%257C%2520Midsummer%2520is%2520Full%2520of%2520Love&vid=s00343f4k3v&defn=fhd&fhdswitch=0&show1080p=0&isHLS=1&dtype=3&sphls=2&spgzip=1&dlver=2&spau=1&spaudio=15&spsrt=1&spvideo=16&defsrc=2&encryptVer=8.1&cKey=58157996EB14DEBC05349F70744E662AE432D09C13685F8DD8BEF69D01C76F7EDA3C600C21FAD398CDB214E63FD13DB07880A5CC69392C832DFCBCB5FF86E94315408CAE323F9EF983B187428100A93571E4D32ABBF66447099EDAECD12C8734AE4B661A1C5EBD9467A4829FC2A726202409385FA645041097059F3692E4400C9779F630BBF0F689A8733D61A20CBD0CA8AA09D2EB55551E52FF3B1C3F34DC06A31CFD1C1B55F0F62F6984A7C9F3AD1D5783759B0EB141BBBD0D84BD65A8333295AA2C7F7A3F91F4A6AC3D269D3C847BFE0F55EFE32D851FB3FFF089E0D20CE41D0CAEB9E7F51EEDE4144DFECD08672B0AD5AF597F6E6A4C9DA77CF7401DED0D701A0D6787B781910F2ADA288A4A3AAA&fp2p=1&spadseg=1

**Comment by wyl5602443** [comment]
WeTV的网站怎么打不开了？已经一周了！！！大陆IP，北美IP都打不开，是我一个人的问题吗？？？

**Comment by nilaoda** [comment]
> WeTV的网站怎么打不开了？已经一周了！！！大陆IP，北美IP都打不开，是我一个人的问题吗？？？

台湾 泰国都正常

**Comment by wyl5602443** [comment]
> > WeTV的网站怎么打不开了？已经一周了！！！大陆IP，北美IP都打不开，是我一个人的问题吗？？？
> 
> 台湾 泰国都正常

网址还是：https://wetv.vip/zh-cn 这个吗？
我用大陆IP和北美IP都打不开了，也不知道什么问题！

**Comment by nilaoda** [comment]
> > > WeTV的网站怎么打不开了？已经一周了！！！大陆IP，北美IP都打不开，是我一个人的问题吗？？？
> > 
> > 
> > 台湾 泰国都正常
> 
> 网址还是：https://wetv.vip/zh-cn 这个吗？
> 我用大陆IP和北美IP都打不开了，也不知道什么问题！

是的

**Comment by wyl5602443** [comment]
> > > > WeTV的网站怎么打不开了？已经一周了！！！大陆IP，北美IP都打不开，是我一个人的问题吗？？？
> > > 
> > > 
> > > 台湾 泰国都正常
> > 
> > 
> > 网址还是：https://wetv.vip/zh-cn 这个吗？
> > 我用大陆IP和北美IP都打不开了，也不知道什么问题！
> 
> 是的

谢谢回复，换泰国IP果然可以了，唉，想看个剧越来越难了！

**Comment by bmw1398** [comment]
你可以试试浏览器的无痕登陆!

wyl5602443 <notifications@github.com>于2020年9月17日 周四12:53写道：

**Comment by Tithen-Firion** [comment]
@NaufalAriqS21 @zackmark29 as long as the `encryptVer` is `8.1` [this code](https://gist.github.com/Tithen-Firion/244bdc4e2ab29ee7aaff4e34ed40b93d) should work. ;) Code both in JavaScript and Python.  
I also made a [pull request](https://github.com/ytdl-org/youtube-dl/pull/26809) for `youtube-dl` but since I don't have a VIP account I can't test if it works with VIP stuff.

And if the encryption version breaks you can still use [this script](https://gist.github.com/Tithen-Firion/e58d22e4b97cdfb90400c5b1ddbfc647) to get the JSON data in your browser.

**Comment by zackmark29** [comment]
> @NaufalAriqS21 @zackmark29 as long as the `encryptVer` is `8.1` [this code](https://gist.github.com/Tithen-Firion/244bdc4e2ab29ee7aaff4e34ed40b93d) should work. ;) Code both in JavaScript and Python.
> I also made a [pull request](https://github.com/ytdl-org/youtube-dl/pull/26809) for `youtube-dl` but since I don't have a VIP account I can't test if it works with VIP stuff.
> 
> And if the encryption version breaks you can still use [this script](https://gist.github.com/Tithen-Firion/e58d22e4b97cdfb90400c5b1ddbfc647) to get the JSON data in your browser.

I hope I also know Python. But I only code in C#. is there any chance to convert they ckey generator? to C#?

**Comment by zackmark29** [comment]
@nilaoda  is there any chance you can share the source code for your wetv tool for C#? I just want to modify for English version and for personal use only.

**Comment by zackmark29** [comment]
> @nilaoda is there any chance you can share the source code for your wetv tool for C#? I just want to modify for English version and for personal use only. Or could you just help how I can generate the CKey?

**Comment by Tithen-Firion** [comment]
@zackmark29 And I don't code in C#. Look, if I was able to turn [this](https://gist.github.com/Tithen-Firion/a01b7a39bc59367d04f26c55f7090d9e) into what I sent earlier, you can rewrite it to C#. Good luck!

**Comment by nilaoda** [comment]
> @nilaoda is there any chance you can share the source code for your wetv tool for C#? I just want to modify for English version and for personal use only.

You can rewrite this to C#.
https://github.com/muumlover/scripts/blob/5d635fb0d4ea24454d5f3b851c6154b2895fa06c/ckey_test/raw/test-8.1.html

**Comment by zackmark29** [comment]
> > @nilaoda is there any chance you can share the source code for your wetv tool for C#? I just want to modify for English version and for personal use only.
> 
> You can rewrite this to C#.
> https://github.com/muumlover/scripts/blob/5d635fb0d4ea24454d5f3b851c6154b2895fa06c/ckey_test/raw/test-8.1.html

Thank you for that @nilaoda 
But I can't figure out how to translate JavaScript to C#. I'm still a beginner.

**Comment by zackmark29** [comment]
> > > @nilaoda is there any chance you can share the source code for your wetv tool for C#? I just want to modify for English version and for personal use only.
> > 
> > 
> > You can rewrite this to C#.
> > https://github.com/muumlover/scripts/blob/5d635fb0d4ea24454d5f3b851c6154b2895fa06c/ckey_test/raw/test-8.1.html
> 
> Thank you for that @nilaoda
> But I can't figure out how to translate JavaScript to C#. I'm still a beginner.

Could you help me @nilaoda  translate it to C# that will work with this url? https://wetv.vip/en/play/8p6njtvfieubdzd/o003412qg8c

**Comment by wyl5602443** [comment]
大神请来看看，这个爱奇艺的这个海外站能像WeTV一样进行解析吗？
https://www.iq.com
