### ISSUE TITLE
【工具】哔哩哔哩下载器

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/Blog#29]
# 项目地址
https://github.com/nilaoda/BBDown

# 演示
![1](https://user-images.githubusercontent.com/20772925/88478847-fe263580-cf7d-11ea-8ad3-b37ceb99fb92.gif)

下载完毕后在当前目录查看MP4文件：

![2](https://user-images.githubusercontent.com/20772925/88478901-5e1cdc00-cf7e-11ea-97c1-154b9226564e.png)

**Comment by 592767809** [comment]
部分无法解析4K，属于正常现象吗？例如：https://www.bilibili.com/video/BV1BT4y1g7mk

**Comment by nilaoda** [comment]
> 部分无法解析4K，属于正常现象吗？例如：https://www.bilibili.com/video/BV1BT4y1g7mk

这种只有网页端才有4K，使用`-tv`就不行了

**Comment by 592767809** [comment]
> > 部分无法解析4K，属于正常现象吗？例如：https://www.bilibili.com/video/BV1BT4y1g7mk
> 
> 这种只有网页端才有4K，使用`-tv`就不行了

原来如此，那这种随缘了，部分能下4K很不错了
