### ISSUE TITLE
【转载】大陆IP在线观看wetv任意地区视频

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/Blog#4]
### 引言
只需用wetv的vid替换{vid} `https://v.qq.com/x/page/{vid}.html`即可  
可播放任意未下线资源，包括wetv、腾讯视频、QQ音乐MV等资源

### 示例

以`我们不能是朋友`无字幕版本(泰区)为例，`https://m.wetv.vip/play?cid=jaqbukliupag2dj&vid=n0031tzago0&languageid=1491963&ptag=1_5122`  

**提示**：上述wetv网址电脑直接打开会提示无法找到视频，可以用`view-source:`查看源代码以获取视频列表。

通过上述地址得到vid列表↓  
`n0031tzago0,x0031bin7nn,m0031wgyurf,g0031eyg8ib,t0031l0z988,a0031zh4vix`
即可拼接出大陆可直接播放的地址：

01：https://v.qq.com/x/page/n0031tzago0.html
02：https://v.qq.com/x/page/x0031bin7nn.html
03：https://v.qq.com/x/page/m0031wgyurf.html
04：https://v.qq.com/x/page/g0031eyg8ib.html
05：https://v.qq.com/x/page/t0031l0z988.html
06：https://v.qq.com/x/page/a0031zh4vix.html

![image](https://user-images.githubusercontent.com/20772925/62408002-090ceb00-b5f4-11e9-9100-20c7cba729a4.png)

再如台湾地区版本`我们不能是朋友`，`https://m.wetv.vip/play?cid=oegn5kfglj1cy0m&vid=d0031uo6ntz&languageid=1491963&ptag=1_5078`

01：https://v.qq.com/x/page/u0030qunx0e.html
02：https://v.qq.com/x/page/v00312cgkj8.html
03：https://v.qq.com/x/page/f0031qh94b7.html
04：https://v.qq.com/x/page/n0031m34kuo.html
05：https://v.qq.com/x/page/u00318j2qb2.html
06：https://v.qq.com/x/page/v003158j09m.html
07：https://v.qq.com/x/page/t0031ljqurw.html
08：https://v.qq.com/x/page/d0031uo6ntz.html
09：https://v.qq.com/x/page/v0031s0usub.html
10：https://v.qq.com/x/page/t0031ccyzab.html

---

QQ音乐MV演示：
`https://y.qq.com/n/yqq/mv/v/b00316lz6qg.html`
可修改为
`https://v.qq.com/x/page/b00316lz6qg.html`

**Comment by HuShanquan3** [comment]
这个和大陆版本有什么不一样呢

**Comment by nilaoda** [comment]
> 这个和大陆版本有什么不一样呢

无字幕

**Comment by liuqiqi79** [comment]
请教大神，iqiyi和youku的海外地区视频有类似的在线观看替换方法吗？

**Comment by wyl5602443** [comment]
请问一下怎么提取爱奇艺，腾讯视频，优酷，WeTV，MGTV以及搜狐这些视频站的M3U8代码的呢？我记得之前有浏览器的JS代码可以解析获取的啊，但是找了很久也没找到。请问能给个地址吗？像这个弄到了在线看的视频地址，但是找不到M3U8地址还是下载不了啊！

**Comment by wyl5602443** [comment]
大陆地区根本搜索不到这些没版权没下线的视频地址啊！

**Comment by awei78** [comment]
是的，现在大陆不能看了，版权问题：
![copy_right](https://user-images.githubusercontent.com/25757989/97524590-0314de00-19e0-11eb-8b4d-8e18ba835a68.png)
