### ISSUE TITLE
【教程】千亿解析 接口分析

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/Blog#5]
先上网址：`https://v.qianyicp.com/v.php?url=https://v.qq.com/x/cover/vbb35hm6m6da1wc/x0031w3jug3.html`  

开始分析：
按下`F12`打开开发人员工具，切换到`Network`选项卡，可以很容易找到，是一个`api.php`的请求获取到了我们需要的视频数据：  

![image](https://user-images.githubusercontent.com/20772925/62764108-afa72f00-babf-11e9-8935-751f13aa1e8b.png)

切换到`Header`选项卡，查看请求参数，发现是个`POST`请求：

![image](https://user-images.githubusercontent.com/20772925/62764206-e7ae7200-babf-11e9-86f6-24704c451789.png)

发送的数据如下：

![image](https://user-images.githubusercontent.com/20772925/62764256-04e34080-bac0-11e9-971b-bb9104f627e0.png)

很明显`url`是我们要解析的视频网址，`time`是一个10位的时间戳，`key`和`key2`应该是解析网站为了防盗链设置的必要参数，`ref`、`type`、`vid`、`lg`四个参数我解析了几个视频发现都一样，先不管他。接下来就是寻找`key`和`key1`是怎么来的

在`Network`选项卡往上翻可以看到请求了一个html页面，即  

![image](https://user-images.githubusercontent.com/20772925/62764886-87b8cb00-bac1-11e9-9773-15ae3397f84f.png)

通过查看当前网页源代码可知播放器是嵌套了一个`iframe`，而上面这个请求就是加载此`iframe`产生的  

![image](https://user-images.githubusercontent.com/20772925/62764990-c189d180-bac1-11e9-889a-4e431f987a97.png)

查看该网址的源代码，就能看到整个请求过程，以及我们需要的`key`和`key2`两个参数的来源：

![image](https://user-images.githubusercontent.com/20772925/62765168-1decf100-bac2-11e9-87e7-1d80af5074d2.png)
 
可以看到`key2`貌似是明文字符串，而`key`是用`desn`算法算出来的，`$('#hdMd5').val()`的是Jquery的语法，用来取出当前页面元素ID为`hdMd5`的值，全局搜索`hdMd5`，轻松找到所需的值：

![image](https://user-images.githubusercontent.com/20772925/62765385-99e73900-bac2-11e9-8f14-b95e4aef74a4.png)

浏览器打开刚才的`iframe`网址，即`https://www.qianyicp.com/?url=https://v.qq.com/x/cover/vbb35hm6m6da1wc/x0031w3jug3.html`，在`Console`选项卡中调用`desn`函数计算`key`：

![image](https://user-images.githubusercontent.com/20772925/62765712-43c6c580-bac3-11e9-83e1-a035e8744579.png)

最后拼接所有的参数，使用原始请求的所有`Header`进行`Post`测试，此时蛋疼的事出现了，并没返回我们所需的视频链接，而是返回来一个很短的视频地址：

![image](https://user-images.githubusercontent.com/20772925/62765937-d0718380-bac3-11e9-9c8d-614975ea07d4.png)

打开一看， 居然是防盗链视频……

![image](https://user-images.githubusercontent.com/20772925/62766031-07e03000-bac4-11e9-84bc-70a17ac85903.png)

emmmm，说明我们刚才操作肯定有哪里不对，经过分析，只有可能是`key`的计算有误。让我们重新回到刚才的网页源代码中仔细观察，大部分函数都是明文写着，基本都是各种加载数据，异步请求之类的，唯独有一个函数被“加密”而且此函数是立即执行函数，由此推断此函数可能做了某些手脚。在`Consloe`中贴入`eval`函数的内容按下回车：

![image](https://user-images.githubusercontent.com/20772925/62766439-0d8a4580-bac5-11e9-810d-d9cb12bdef72.png)

果然，是这行代码使用Jquery修改了`hdMd5`控件的值，导致上面的计算错误，`key`也就错了……使用这个新的值重复上述过程，即可获得正确数据：

![image](https://user-images.githubusercontent.com/20772925/62767024-57276000-bac6-11e9-9ed6-19d71912f6ff.png)

最后，经过测试，只需要`X-Requested-With:XMLHttpRequest`和`Content-Type:application/x-www-form-urlencoded; charset=UTF-8`即可完成请求。

**Comment by nilaoda** [comment]
上述过程的程序实现：[qianyicp.zip](https://github.com/nilaoda/Blog/files/3485557/qianyicp.zip)

![image](https://user-images.githubusercontent.com/20772925/62767605-a5892e80-bac7-11e9-9378-98d4101b260c.png)

支持两种方式使用：
- 双击后输入视频地址回车
- 命令行 `qianyicp.exe 视频地址`

**Comment by xtcs001** [comment]
未经处理的异常:  System.IO.FileLoadException: 未能加载文件或程序集“Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。句柄无效。 (异常来自 HRESULT:0x80070006 (E_HANDLE))
   在 qianyicp.Program.Main(String[] args)

**Comment by plmxs2017** [comment]
未经处理的异常:  System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 183.60.197.162:443
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 System.Net.WebClient.DownloadString(String address)
   在 qianyicp.Program.Main(String[] args)


老大出现错误啊。

**Comment by nilaoda** [comment]
他网站升级了

**Comment by plmxs2017** [comment]
老大，能否支持HBOGO KKTV的解析啊。。

**Comment by nilaoda** [comment]
现在请求地址需更改为`https://vip.qianyicp.com/?url=xxx`，同时需要设置`Referfer`为`https://v.qianyicp.com/v.php?url=xxx`。

**Comment by nilaoda** [comment]
> 老大，能否支持HBOGO KKTV的解析啊。。

想多了 我没这个本事……

**Comment by plmxs2017** [comment]
老大还行不行。显示连接已经关闭。

**Comment by SSDYBB** [comment]
为啥进这网站开F12，然后CPU满载，占用率100%，浏览器直接卡死，是电脑太差了吗？其他网站没有这问题

**Comment by nilaoda** [comment]
> 为啥进这网站开F12，然后CPU满载，占用率100%，浏览器直接卡死，是电脑太差了吗？其他网站没有这问题

今天我也是这样，管他呢 直接用他的接口就行了

**Comment by SSDYBB** [comment]
![1](https://user-images.githubusercontent.com/40603576/62842672-3c333680-bce6-11e9-871a-6970a3fbd5e9.png)
优酷和爱奇艺的m3u8显示不完整，可以更新一下吗？

**Comment by plmxs2017** [comment]
请问老大，解析出来的都是720P吗？
