### ISSUE TITLE
【C#】优酷更改清晰度及分辨率有效性验证

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/Blog#7]
```C#
//获取地址
public static string MakeUrl(string url, string f)
{
    string returnS = "";
    if (f.Contains("mp5") || f.Contains("hls5"))
    {
        if (!url.Contains("streamcoding=h265"))
        {
            returnS = url.Replace(GetQueryString("type", url) + "", f).Replace("&duration", "&streamcoding=h265&duration");
        }
        else
        {
            returnS = url.Replace(GetQueryString("type", url) + "", f);
        }
    }
    else
    {
        if (url.Contains("streamcoding=h265"))
        {
            returnS = url.Replace(GetQueryString("type", url) + "", f).Replace("&streamcoding=h265", "");
        }
        else
        {
            returnS = url.Replace(GetQueryString("type", url) + "", f);
        }
    }
    return returnS;
}

//验证分辨率是否存在
public static bool CheckUrl(string url)
{
    string useLess = GetUrlFileName(Regex.Match(new WebClient().DownloadString(MakeUrl(url, "flvhdv3")), "http.*\\.ts").Value);
    WebClient wb = new WebClient();
    string m3u8 = wb.DownloadString(url);
    string fileName = GetUrlFileName(Regex.Match(m3u8, "http.*\\.ts").Value);
    if (!(m3u8.Length < 100 || fileName == useLess))
    {
        return true;
    }
    return false;
}
```

调用实例：

```C#
//尝试改4K
if (!v.m3u8.Contains("type=mp5hd4"))
{
    string url = MakeUrl(v.m3u8, "mp5hd4v3");
    if (CheckUrl(url))
    {
        v.m3u8 = url;
    }
}
```

**Comment by liuqiqi79** [comment]
直接在浏览器页面操作吗？老大可否教一下具体操作步骤？

**Comment by liuqiqi79** [comment]
已获取m3u8地址如：http://pl.cp31.ott.cibntv.net/playlist/m3u8?vid=XNDQyODk2OTU2MA&type=mp5hd4v3&ups_client_netip=ded801ec&utid=Xh5342tdqegDAGghILCUatHF&ccode=0103010102&psid=e0308f9a6541e0413d74570bec787e8d&ups_userid=1065568523&ups_ytid=1065568523&pid=e849fea79a704c06&streamcoding=h265&app_ver=2120705392&duration=2661&expire=18000&drm_type=7&drm_device=4&advIds=1109948472_106-1108319768_106&play_ability=4096&device_uuid=E8BAC0E48C0925C926FF79C6A9C79D79&ups_ts=1579059276&onOff=2&encr=1&ups_key=c3057792c5d38b4f24dfd4da2df127e6&Host=pl.cp31.ott.cibntv.net&Cache-Control=no-cache%2Cno-store&Pragma=no-cache&User-Agent=ott_android_tv_proxy%3B2.0.4.26.2%3BAndroid%3B5.1.1%3Bsamsung&Connection=close
是直接把mp5hd4v3改为hls5hd4_hfr_hbr吗？试过，不成功。请教老大具体怎么改清晰度和分辨率呢？

**Comment by nilaoda** [comment]
> 已获取m3u8地址如：http://pl.cp31.ott.cibntv.net/playlist/m3u8?vid=XNDQyODk2OTU2MA&type=mp5hd4v3&ups_client_netip=ded801ec&utid=Xh5342tdqegDAGghILCUatHF&ccode=0103010102&psid=e0308f9a6541e0413d74570bec787e8d&ups_userid=1065568523&ups_ytid=1065568523&pid=e849fea79a704c06&streamcoding=h265&app_ver=2120705392&duration=2661&expire=18000&drm_type=7&drm_device=4&advIds=1109948472_106-1108319768_106&play_ability=4096&device_uuid=E8BAC0E48C0925C926FF79C6A9C79D79&ups_ts=1579059276&onOff=2&encr=1&ups_key=c3057792c5d38b4f24dfd4da2df127e6&Host=pl.cp31.ott.cibntv.net&Cache-Control=no-cache%2Cno-store&Pragma=no-cache&User-Agent=ott_android_tv_proxy%3B2.0.4.26.2%3BAndroid%3B5.1.1%3Bsamsung&Connection=close
> 是直接把mp5hd4v3改为hls5hd4_hfr_hbr吗？试过，不成功。请教老大具体怎么改清晰度和分辨率呢？

不是每个视频都有的

**Comment by liuqiqi79** [comment]
> > 已获取m3u8地址如：http://pl.cp31.ott.cibntv.net/playlist/m3u8?vid=XNDQyODk2OTU2MA&type=mp5hd4v3&ups_client_netip=ded801ec&utid=Xh5342tdqegDAGghILCUatHF&ccode=0103010102&psid=e0308f9a6541e0413d74570bec787e8d&ups_userid=1065568523&ups_ytid=1065568523&pid=e849fea79a704c06&streamcoding=h265&app_ver=2120705392&duration=2661&expire=18000&drm_type=7&drm_device=4&advIds=1109948472_106-1108319768_106&play_ability=4096&device_uuid=E8BAC0E48C0925C926FF79C6A9C79D79&ups_ts=1579059276&onOff=2&encr=1&ups_key=c3057792c5d38b4f24dfd4da2df127e6&Host=pl.cp31.ott.cibntv.net&Cache-Control=no-cache%2Cno-store&Pragma=no-cache&User-Agent=ott_android_tv_proxy%3B2.0.4.26.2%3BAndroid%3B5.1.1%3Bsamsung&Connection=close
> > 是直接把mp5hd4v3改为hls5hd4_hfr_hbr吗？试过，不成功。请教老大具体怎么改清晰度和分辨率呢？
> 
> 不是每个视频都有的

只需直接修改mp5hd4v3改为hls5hd4_hfr_hbr即可？如果修改后能成功，证明有。不成功则没有，是这个意思吗？
小白不懂怎么运行代码。。。请老大不吝赐教。

**Comment by xwlcn** [comment]
这种东西分享就容易G，现在好了，除了DRM解密没有其他办法了。

**Comment by wansqh** [comment]
DecodeKey现在怎么获取
