### ISSUE TITLE
【工具】一键获取腾讯视频全集地址

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/Blog#8]
# 应求发布
* 支持腾讯视频
* 支持Wetv
* 不支持综艺节目等
---

![image](https://user-images.githubusercontent.com/20772925/70889214-fe8c4480-201c-11ea-82e1-31ce5ef86db6.png)

---
[QQVid_20191216.zip](https://github.com/nilaoda/Blog/files/3966628/QQVid_20191216.zip)

[QQVid_20200109.zip](https://github.com/nilaoda/Blog/files/4040768/QQVid_20200109.zip)

[QQVid_20200116.zip](https://github.com/nilaoda/Blog/files/4069983/QQVid_20200116.zip)

**Comment by nilaoda** [comment]
仅支持`win-x64`

**Comment by zackmark29** [comment]
why it's not working with this link?
https://wetv.vip/en/play/tfzx5m7vesn1tjv/h0031r1kfm1

**Comment by liusmallnew** [comment]
一键获取腾讯视频全集地址之后呢？这些地址有啥用？是用来批量下载视频吗
